### ISSUE TITLE
Need a verbose message on duplicated and dropped observations after countryid standardization

### ISSUE THREAD

**Issue by LaDilettante** [rOpenGov/psData#21]
When using `psData`, the user would frequently see messages such as:

> 37 duplicated values were created when standardising the country ID with iso2c.
> 59 observations dropped based on missing values of the standardised ID variable.

I think it would be a good idea to add a `verbose` option that allows user to know exactly which id has been dropped / duplicated due to transforming which type of country ID to another. It would add a lot of peace of mind. In my experience, I always go back to check what has been dropped manually.

If @christophergandrud think this is a good idea, I would be happy to contribute a pull request.

**Comment by christophergandrud** [comment]
Sounds good to me.
