### ISSUE TITLE
Is this package still usable?

### ISSUE THREAD

**Issue by joufeihuang** [rOpenGov/psData#30]
Hello, I am not sure if this package is still usable?
I tried to run the code, yet, R shows warning and said there is no "WinsetCreator".

**Comment by antagomir** [comment]
@christophergandrud is probably the best developer to comment on this one.

**Comment by christophergandrud** [comment]
I haven't actively maintained this package for years. I assume that some of it might be useable, but make no guarantees.

**Comment by briatte** [comment]
I just checked the dev branch, and a lot of what I was planning to do in there has been superseded by `dplyr`, `tibble` and `tsibble`. It was fun to work on this project, though, I believe it taught me S3 classes back then!

@joufeihuang out of curiosity, which functions were of interest to you? I'm always curious to know what political science-oriented functions are on request.
